name: Deploy api-test API to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install dependencies
      run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

    - name: Deploy to server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        rsync -avz -e "ssh -i private_key" --exclude=node_modules --exclude=.git ./ $SSH_USERNAME@$SERVER_IP:/var/www/html/api-test
        ssh -i private_key $SSH_USERNAME@$SERVER_IP "cd /var/www/html/api-test && composer install --no-dev && php artisan migrate --force && php artisan config:cache && php artisan route:cache"
